server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  port: 8091

logging:
  level:
    root: INFO

spring:
  jmx:
    enabled: false
  profiles:
    active: dev
  application:
    name: door-applets-bg-high-version
  ai: # spring-ai-alibaba
    dashscope:
      api-key: ${ai.dashscope-deepseek.api-key}
    openai:
      api-key: ${ai.openai-deepseek.api-key}
      base-url: ${ai.openai-deepseek.url}
      chat:
          embedding:
            enabled: false

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.swimmingliu.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# 上下文记忆功能
memory:
  mysql:
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}

